language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: uqXvK78p3Co4neDLQOchB06bpWgt46EtSwQYMTkLyrQOJpgrz8uekFTPjws3pXRLCLL2PZ/e7vnlPXuhnJtNGmD6f1oBtWjzovQsHXqE9twly6Na0AszD+4wwabG6ht8MQJNZH1vcTAgkB4P9tsvHdEuAWwsIEpRmVzdM/TRCaWgnf9Wfd+d7FDL+zz83bZDMLsj4grH8lqF5ZFKL2I5qvoPyCifoup0siHOMw37JSr1O2WFtUr/Qxe/toL6P7o2XiqKbKaVfKwEbYTrC2JmzXWWd3zFXA6ChonFcWwLlUxXP9SVVYCDezKk7Z3FP7qYAIF5mTe6lAlIErBBRMPdz4XEeuZ4JOL3Hn6IMJRffYYjX/6ETEY1OBxlajxfacorNAFQVOHLpxhhHdITJm9E9bu7blp6tGJbc37e4iIVI0CrX0eb5vHuAJVzjHrT+mOrjuYMmLMAch7BhWKzjN+OSH04uc2lq2kG80KwPHqakvncglSZK1ykGHTixfdA6yrWeZP6+KLFRbx8hfM/GsPoP+47teDqzdDMUr7/lAfSHQ6ag13c8GYlSzRoBN4SSd4v2+q8dQD2VUKw4IJFFZnuWLrlOiTX0XtyE66CqmMwfhTiGGgJe8v38cX+nmsy6N+ynuaoY0U6PVnr/fbzLoqUzLxSBNR0HPlsOvHxhlNpbi4=
  app: intense-ocean-98731
  on:
    repo: riceball1/blog-app-mongoose-challenge-solution
